### ISSUE TITLE
Compiler warning in Angular project

### ISSUE THREAD

**Issue by adamkasztenny** [Marak/faker.js#730]
I'm using [mocker-data-generator](https://github.com/danibram/mocker-data-generator), which seems to bundle faker 4.1.0 with it, and I'm getting this error when compiling (through `npm start`, which calls `ng serve`):
```
WARNING in ./node_modules/faker/locale/ReadMe.md
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| # Read Me
| 
| The files in this directory have been auto-generated from the `gulpfile`.
ℹ ｢wdm｣: Compiled with warnings.
```
I [commented on an issue](https://github.com/danibram/mocker-data-generator/pull/33) with that project as well. Is this something on my end? Thanks in advance.

Edit: The problem is here: https://github.com/npm/npm-packlist/pull/5/files. npm refuses to ignore any files called `readme` (with any case) with any extension. You should either move `locale/ReadMe.md` somewhere else (that isn't published), or rename the file and add it to `.npmignore`. See [this](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) as well. Thanks.

**Comment by adamkasztenny** [comment]
@mesche This is supposedly fixed in `5.0.0.`, according to [this](https://github.com/Marak/faker.js/pull/796#issuecomment-678889140)

**Comment by Marak** [comment]
Thank you for your contributions @adamkasztenny 

Please let us know if you can still find any issues.

Closing for now.

**Comment by raman-nbg** [comment]
I still get this error with version `5.3.1` in combination with the latest angular version `12.0.2`.

```
./node_modules/faker/locale/ReadMe.md:1:1 - Error: Module parse failed: Unexpected character ' ' (1:1)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> # Read Me
| 
| The files in this directory have been auto-generated from the `gulpfile`.
```

**Comment by shuZro** [comment]
> I still get this error with version `5.3.1` in combination with the latest angular version `12.0.2`.
> 
> ```
> ./node_modules/faker/locale/ReadMe.md:1:1 - Error: Module parse failed: Unexpected character ' ' (1:1)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> > # Read Me
> | 
> | The files in this directory have been auto-generated from the `gulpfile`.
> ```
> 
> Edit: With angular 12 comes webpack 5. It seems like that the webpack configuration in angular changed. webpack tries to load and parse the `ReadMe.md` of faker.

Any fix for this?

**Comment by raman-nbg** [comment]
> Any fix for this?

I added this command as a postinstall script to my scripts in `package.json`

```json
"postinstall": "rm ./node_modules/faker/locale/ReadMe.md"
```

This is not a clean solution but at least it works... 🤷‍♂️
